name: Pipeline Site HTML

on:
  push:
    branches: [ "main" ]
    workflow-dispatch:

jobs:

  verification:
    runs-on: ubuntu-latest
    steps:
      - name: RÃ©cupÃ©rer le code
        uses: actions/checkout@v4

      - name: VÃ©rifier la prÃ©sence du fichier index
        run: |
          if [ -f "index.html" ]; then
            echo "ðŸŸ¢ Le fichier index.html a Ã©tÃ© trouvÃ© !"
          else
            echo "ðŸ”´ ERREUR : index.html est introuvable Ã  la racine du projet."
            exit 1
          fi


  deploy:
    runs-on: ubuntu-latest
    needs: verification
    environment: production
    steps:
      - name: DÃ©ploiement
        run: echo "ðŸš€ Votre site HTML est en cours de dÃ©ploiement sur le serveur !"